name: verify

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop

jobs:
  verify:
    runs-on: ubuntu-latest
    name: verify
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 10.22.0
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm
      - uses: actions/setup-python@v7
        with:
          python-version: "3.10"
      - name: Install root dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Verify standard
        run: pnpm verify:standard
